import FWCore.ParameterSet.Config as cms

inclusiveJetAnalyzer = cms.EDAnalyzer(
    "HiInclusiveJetAnalyzer",
    jetTag = cms.InputTag("ak4PFJets"),
    jetPtMin = cms.double(5.0),
    matchTag = cms.untracked.InputTag("akPu4PFpatJets"),
    genjetTag = cms.InputTag("ak4HiGenJets"),
    eventInfoTag = cms.InputTag("generator"),
    isMC = cms.untracked.bool(False), 
    useOnlyMatched = cms.untracked.bool(False), 
    fillGenJets = cms.untracked.bool(False),
    rParam = cms.double(0.4),
    pfCandidateLabel = cms.untracked.InputTag('packedPFCandidates'),
    trackQuality  = cms.untracked.string("highPurity"),
    vtxTag = cms.InputTag("hiSelectedVertex"),
    saveRawPt = cms.untracked.bool(True),
    useHepMC = cms.untracked.bool(False),
    useQuality = cms.untracked.bool(True),
    doGenTaus = cms.untracked.bool(False),
    doGenSym = cms.untracked.bool(False),
    doSubJets = cms.untracked.bool(False),
    doJetConstituents = cms.untracked.bool(False),
    doWTARecluster = cms.untracked.bool(False),
    doHiJetID = cms.untracked.bool(False),
    doStandardJetID = cms.untracked.bool(False),
    doSubEvent = cms.untracked.bool(False),
    doLegacyBtagging = cms.untracked.bool(False),
    doCandidateBtagging = cms.untracked.bool(False),
    )
